package com.quiz.model;

/**
 * Wraps the feedback text associated with a quiz result.
 * Generated by FeedbackGenerator from the grade.
 */
public class Feedback {

    private final String grade;
    private final String label;       // e.g. "Excellent", "Good"
    private final String message;     // detailed motivational message

    public Feedback(String grade, String label, String message) {
        this.grade   = grade;
        this.label   = label;
        this.message = message;
    }

    public String getGrade()   { return grade; }
    public String getLabel()   { return label; }
    public String getMessage() { return message; }

    @Override
    public String toString() {
        return "Feedback{grade='" + grade + "', label='" + label + "'}";
    }
}
